# Build customization
build:
  # Path to main.go file.
  # Default is `main.go`
  main: ./cmd/kubefwd/kubefwd.go
  binary: kubefwd

  env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
  - CGO_ENABLED=0

  # GOOS list to build in.
  # For more info refer to https://golang.org/doc/install/source#environment
  # Defaults are darwin and linux
  goos:
  - linux
  - darwin
  - arm
  - windows

  # GOARCH to build in.
  # For more info refer to https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64
  goarch:
  - amd64
  - arm

  ldflags: -s -w -X main.Version={{.Version}}

release:
  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false

  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: false

  # You can change the name of the GitHub release.
  # Default is ``
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  disable: false

# Archive customization
archive:
  # You can change the name of the archive.
  # This is parsed with Golang template engine and the following variables.
  name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"

  # Archive format. Valid options are `tar.gz` and `zip`.
  # Default is `zip`
  format: tar.gz

  # Replacements for GOOS and GOARCH on the archive name.
  # The keys should be valid GOOS or GOARCH values followed by your custom
  # replacements.
  # By default, `replacements` replace GOOS and GOARCH values with valid outputs
  # of `uname -s` and `uname -m` respectively.
  replacements:
    amd64: amd64
    386: 386
    darwin: Darwin
    linux: linux

  format_overrides:
  - goos: windows
    format: zip

  # Additional files you want to add to the archive.
  # Defaults are any files matching `LICENCE*`, `LICENSE*`,
  # `README*` and `CHANGELOG*` (case-insensitive)
  files:
  - LICENSE
